services:
  postgres:
    image: postgres:16
    container_name: messenger-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: mydb
    volumes:
      - ./db:/docker-entrypoint-initdb.d
